baseURL = "https://players1st.github.io/blog/"
languageCode = "en-us"
title = "Players1st Blog"
theme = "parsa"
summaryLength = "10"
paginate = 6
publishDir = "docs"

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# navigation
[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 3

[params]
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "This is meta description"
# Preloader
# preloader = true

# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"
