baseURL = "https://blog.players1.st/"
languageCode = "ja-jp"
title = "Players1st(プレイヤーズファースト) Blog"
theme = "parsa"
summaryLength = "4"
paginate = 6
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
name = "About"
URL = "https://about.players1.st/"
weight = 2

[[menu.main]]
name = "Contact"
URL = "https://players1.st/feedbacks/new"
weight = 3

[params]
logo = "images/P1st_logo.jpg"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
title = "Players1st(プレイヤーズファースト) Blog"
description = "Players1st(プレイヤーズファースト) Blog |「スポーツの資金難を解決する」スポーツファンディング 投げ銭、月額スポンサー、スポンサー限定ポストでファンを増やします。アスリート・クラブチームをしっかり支援"
images = ["images/P1st_logo.jpg"]
# Preloader
preloader = true
# search
search = false
# about author
author = "Players1st"
author_image = "images/P1st_logo.jpg"
bio = "「スポーツの資金難を解決する」スポーツファンディング 投げ銭、月額スポンサー、スポンサー限定ポストでファンを増やします。アスリート・クラブチームをしっかり支援"
# Contact info
# mobile = ""
# email = "exmaple@ymail.com"
company = "株式会社プレイヤーズファースト https://company.players1.st/"
service = "https://players1.st"
address = "東京都世田谷区, 日本"
# Contact Form Action
# contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "UA-73836462-6"
# copyright
copyright = "Copyright &copy; [Players1st, inc.](https://company.players1.st)"

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/players1st.web"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/pys1st"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/players1st.web/"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/company/%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BE%E3%83%97%E3%83%AC%E3%82%A4%E3%83%A4%E3%83%BC%E3%82%BA%E3%83%95%E3%82%A1%E3%83%BC%E3%82%B9%E3%83%88-players1st-inc."
